/*
* generated by Xtext
*/
package org.sonatype.maven.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DependencyDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
