/*
 * generated by Xtext
 */
package org.sonatype.maven;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DependencyDslRuntimeModule extends org.sonatype.maven.AbstractDependencyDslRuntimeModule {

}
