/*
* generated by Xtext
*/
package org.sonatype.maven.contentassist;

import org.sonatype.maven.contentassist.AbstractDependencyDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DependencyDslProposalProvider extends AbstractDependencyDslProposalProvider {

}
